#!/bin/zsh

set -euo pipefail

script_dir="${0:A:h}"
project_dir="${script_dir:h}"
output_dir="$project_dir/public/audio/voice"
temporary_dir="$(mktemp -d /private/tmp/paceforge-voice.XXXXXX)"

trap 'rm -rf "$temporary_dir"' EXIT
mkdir -p "$output_dir"

generate_voice() {
  local filename="$1"
  local message="$2"
  local aiff_file="$temporary_dir/$filename.aiff"

  say -v Yuna -r 230 -o "$aiff_file" "$message"
  afconvert "$aiff_file" "$output_dir/$filename.wav" -f WAVE -d LEI16@22050
}

generate_voice "prep" "운동을 시작합니다. 준비하세요."
generate_voice "rest-suffix" "초 휴식입니다."
generate_voice "set" "운동 시작입니다."
generate_voice "interval" "인터벌 시작입니다."
generate_voice "tabata" "타바타 시작입니다."
generate_voice "custom" "운동 시작입니다."
generate_voice "emom" "이맘 시작입니다."
generate_voice "fortime" "포 타임 시작입니다."
generate_voice "amrap" "에이맵 시작입니다."
generate_voice "warning" "십 초 후 시작합니다. 준비하세요."
generate_voice "paused" "일시정지했습니다."
generate_voice "resume" "계속합니다."
generate_voice "timecap" "타임캡입니다. 운동을 종료합니다."
generate_voice "complete" "운동이 종료되었습니다. 수고하셨습니다."
generate_voice "output-test" "스피커 연결이 정상입니다."

generate_voice "hyrox-01" "런 일 시작입니다."
generate_voice "hyrox-02" "스키 에르그 시작입니다."
generate_voice "hyrox-03" "런 이 시작입니다."
generate_voice "hyrox-04" "슬레드 푸시 시작입니다."
generate_voice "hyrox-05" "런 삼 시작입니다."
generate_voice "hyrox-06" "슬레드 풀 시작입니다."
generate_voice "hyrox-07" "런 사 시작입니다."
generate_voice "hyrox-08" "버피 브로드 점프 시작입니다."
generate_voice "hyrox-09" "런 오 시작입니다."
generate_voice "hyrox-10" "로우 시작입니다."
generate_voice "hyrox-11" "런 육 시작입니다."
generate_voice "hyrox-12" "파머스 캐리 시작입니다."
generate_voice "hyrox-13" "런 칠 시작입니다."
generate_voice "hyrox-14" "샌드백 런지 시작입니다."
generate_voice "hyrox-15" "런 팔 시작입니다."
generate_voice "hyrox-16" "월 볼 시작입니다."

generate_voice "number-0" "영"
generate_voice "number-1" "일"
generate_voice "number-2" "이"
generate_voice "number-3" "삼"
generate_voice "number-4" "사"
generate_voice "number-5" "오"
generate_voice "number-6" "육"
generate_voice "number-7" "칠"
generate_voice "number-8" "팔"
generate_voice "number-9" "구"
generate_voice "number-10" "십"
generate_voice "number-100" "백"
generate_voice "number-1000" "천"

generate_voice "exercise-burpee" "버피 시작입니다."
generate_voice "exercise-air-squat" "에어 스쿼트 시작입니다."
generate_voice "exercise-squat" "스쿼트 시작입니다."
generate_voice "exercise-push-up" "푸시업 시작입니다."
generate_voice "exercise-lunge" "런지 시작입니다."
generate_voice "exercise-plank" "플랭크 시작입니다."
generate_voice "exercise-mountain-climber" "마운틴 클라이머 시작입니다."
generate_voice "exercise-jumping-jack" "점핑 잭 시작입니다."
generate_voice "exercise-kettlebell-swing" "케틀벨 스윙 시작입니다."
generate_voice "exercise-deadlift" "데드리프트 시작입니다."
generate_voice "exercise-snatch" "스내치 시작입니다."
generate_voice "exercise-clean" "클린 시작입니다."
generate_voice "exercise-thruster" "쓰러스터 시작입니다."
generate_voice "exercise-row" "로잉 시작입니다."
generate_voice "exercise-run" "러닝 시작입니다."

echo "Generated PACEFORGE Korean voice assets in $output_dir"
